export enum MUTATIONS {
  setTable = 'setTable',
  setColumns = 'setColumns',
  setMinVariantionColumns = 'setMinVariantionColumns',
  setColumnStimulant = 'setColumnStimulant',
  setColumnWeight= 'setColumnWeight',
  addColumn = 'addColumn',
  setRows = 'setRows',
  addRow = 'addRow',
  deleteRow = 'deleteRow',
  editRow = 'editRow',
  addField = 'addField',
  setMinVariantion = 'setMinVariantion',
  changeDestimulantsToStimulants = 'changeDestimulantsToStimulants',
}