export enum MUTATIONS {
  setTable = 'setTable',
  setColumns = 'setColumns',
  setMinVariantionColumns = 'setMinVariantionColumns',
  setColumnStimulant = 'setColumnStimulant',
  setColumnWeight= 'setColumnWeight',
  addColumn = 'addColumn',
  deleteColumn = 'deleteColumn',
  changeColumnName = 'changeColumnName',
  setRows = 'setRows',
  setCalculationRows = 'setCalculationRows',
  addRow = 'addRow',
  deleteRow = 'deleteRow',
  editRow = 'editRow',
  addField = 'addField',
  setMinVariantion = 'setMinVariantion',
  changeDestimulantsToStimulants = 'changeDestimulantsToStimulants',
  standardize = 'standardize',
  setPatternAndAntipattern = 'setPatternAndAntipattern',
  weighValues = 'weighValues',
  setSyntheticMeasuresOfDevelopment = 'setSyntheticMeasuresOfDevelopment',
  setChartData = 'setChartData',
}